use_frameworks!

target 'CCChartView_Example' do
  pod 'CCChartView', :path => '../'

  target 'CCChartView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
